Update device sample definitions
open-ephys/ONI pull request #53
Opened 2024-11-19 16:43 UTC by aacuevas

- Change hub conter name
- Split write and read frames
- Fixes #51

2024-11-19 16:59 UTC, jonnew commented on source/hw-spec/devices/sample.rst
> +    var       hayload
🐴  🐴  🐴  🐴

2024-11-19 17:00 UTC, jonnew commented on source/hw-spec/devices/sample.rst
> +Write samples MUST have the following format.
I think this can be merged with #54 because i mention some stuff about conforming device datasheet i think. Same true for write frames.

2024-11-19 17:01 UTC, jonnew requested changes
See my comments

2024-11-21 02:32 UTC, aacuevas commented
Comments addressed

2024-11-21 14:27 UTC, jonnew approved these changes

2024-11-21 14:27 UTC, merged